import * as yup from 'yup';

const examProtocolSchema = yup.object().shape({
  child_full_name: yup.string().required(),
  main_complaints_from_parents: yup.string().required(),
  for_what_purpose_did_you_turn_to_a_speech_therapist: yup.string().required(),
  sat_in: yup.string().required(),
  crawled_on_all_fours_into: yup.string().required(),
  went_to: yup.string().required(),
  learned_to_jump_on_two_legs_in: yup.string().required(),
  injury_infection_before_during_and_or_after_childbirth: yup
    .string()
    .required(),
  babbling_in: yup.string().required(),
  first_words_in: yup.string().required(),
  first_short_phrases_in: yup.string().required(),
  speech_environment: yup.string().required(),
  neurological_status: yup.string().required(),
  vision: yup.string().required(),
  hearing: yup.string().required(),
  eating_behavior: yup.string().required(),
  present_and_past_diseases: yup.string().required(),
  drug_treatment: yup.string().required(),
  emotional_and_psychological_level: yup.string().required(),
  emotional_background_during_class: yup.string().required(),
  motivation_and_interest: yup.string().required(),
  mimic_manifestations: yup.string().required(),
  basic_emotions_that_it_exhibits: yup.string().required(),
  formation_of_ideas_about_world_around: yup.string().required(),
  in_a_time_space_situation: yup.string().required(),
  image_i: yup.string().required(),
  somatognosis: yup.string().required(),
  speech_comprehension_level: yup.string().required(),
  level_of_vocabulary_formation: yup.string().required(),
  active_semantic_component_active_vocabulary: yup.string().required(),
  systemic_vocabulary_organization: yup.string().required(),
  level_of_grammatical_competence_formation: yup.string().required(),
  inflectional_skills_and_abilities_part_one: yup.string().required(),
  inflectional_skills_and_abilities_part_two: yup.string().required(),
  level_of_formation_of_phonetic_phonological_competence: yup
    .string()
    .required(),
  state_of_phonemic_perception: yup.string().required(),
  state_of_phonemic_hearing: yup.string().required(),
  phonological_sound_analysis_and_synthesis_skills: yup.string().required(),
  syllabic_structure_of_a_word: yup.string().required(),
  prosodic_side_of_speech: yup.string().required(),
  voice: yup.string().required(),
  smoothness: yup.string().required(),
  pace: yup.string().required(),
  speech_is_carried_out: yup.string().required(),
  breath: yup.string().required(),
  rhythm: yup.string().required(),
  understanding_the_text: yup.string().required(),
  text_production: yup.string().required(),
  reproduction_of_text: yup.string().required(),
  articulation_apparatus_structure: yup.string().required(),
  syntactic_skills_and_abilities: yup.string().required(),
  level_of_formation_of_phonemic_perception: yup.string().required(),
  state_of_phonemic_hearing_game_magic_exam: yup.string().required(),
  formation_of_the_skills_of_sound_analysis_and_synthesis: yup
    .string()
    .required(),
  syllabic_structure_of_the_word: yup.string().required(),
  sound_articulating_side_of_speech: yup.string().required(),
  prosodic_side_of_speech_game_on_the_farm_part_three: yup.string().required(),
  smoothness_game_on_the_farm_part_three: yup.string().required(),
  pace_game_on_the_farm_part_three: yup.string().required(),
  speech_game_on_the_farm_part_three: yup.string().required(),
  breath_game_on_the_farm_part_three: yup.string().required(),
  rhythm_game_on_the_farm_part_three: yup.string().required(),
  understanding_the_text_game_how_the_mouse_could_not_sleep: yup
    .string()
    .required(),
  text_production_game_how_the_mouse_could_not_sleep: yup.string().required(),
  reproduction_of_text_game_how_the_mouse_could_not_sleep: yup
    .string()
    .required(),
  articulation_apparatus_structure_game_how_the_mouse_could: yup
    .string()
    .required(),
  bilateral_motor_organization: yup.string().required(),
  simultaneous_visual_perception: yup.string().required(),
  attention: yup.string().required(),
  general_ideas_of_child_about_world_around_him: yup.string().required(),
  volume_vocabulary: yup.string().required(),
  system_organization_of_dictionary_associative_links: yup.string().required(),
  inflectional_skills_and_abilities: yup.string().required(),
  word_building_skills_and_abilities: yup.string().required(),
  syllabic_structure_of_word: yup.string().required(),
  prosodic_speech_design: yup.string().required(),
  motor_functions_of_articulatory_apparatus: yup.string().required(),
  oral_praxis: yup.string().required(),
  articulatory_praxis: yup.string().required(),
  speech_breathing_and_voice_production: yup.string().required(),
  exhalation_force: yup.string().required(),
  inspiratory_expiratory_differentiation: yup.string().required(),
  basic_motor_skills_and_state_of_coordinating_sphere: yup.string().required(),
  postural_control_of_calm_state: yup.string().required(),
  bilateral_motor_coordination: yup.string().required(),
  formation_of_motor_imitation: yup.string().required(),
  motor_functions_of_hands_and_fingers: yup.string().required(),
  verbal_memory: yup.string().required(),
  speech_attention: yup.string().required(),
  thinking_verbal_and_non_verbal_intelligence: yup.string().required(),
  features_of_early_speech_development: yup.string().required(),
  features_of_speech_environment_in_which_child: yup.string().required(),
  features_of_speech_behavior: yup.string().required(),
  neurological_status_and_condition: yup.string().required(),
  information_about_current_and_past_diseases: yup.string().required(),
  emotional_reaction: yup.string().required(),
  emotional_response_to_adult_emotion: yup.string().required(),
  in_case_of_failure_behaves: yup.string().required(),
  logopedic_conclusion: yup.string().required(),
  recommendation: yup.string().required(),
});

export default examProtocolSchema;

// {
//   "id": "7fed276f-f05f-40e2-a0af-fc9455ed1af9",
//   "game_pictures_for_fish": {
//     "id": "2e171047-ed35-43ae-a7a6-043e5ea2d21e",
//     "shop_hay_cornflower": "works",
//     "dog_pump_lock_goat": "works",
//     "starling_heron_finger": "works",
//     "detective_tongs_garlic": "works",
//     "pike_things_bream": "works",
//     "beetle_soot_scissors": "works",
//     "fur_coat_cat_reed_freckles": "works",
//     "sibilant_parasigmatism": true,
//     "replacing_s_with": "works",
//     "replacing_s_soft_with": "works",
//     "replacing_z_with": "works",
//     "replacing_z_soft_with": "works",
//     "replacing_c_with": "works",
//     "replacing_ch_with": "works",
//     "prominent_sigmatism": true,
//     "nasal_sigmatism": true,
//     "hissing_sigmatism": false,
//     "lateral_sigmatism": false,
//     "labiodental_pronunciation_of_whistling": false,
//     "skip_whistling_sound": true,
//     "mixing_sounds": true,
//     "interdental_sigmatism": true,
//     "replacing_shch_to": "works",
//     "replacing_zh_to": "works",
//     "replacing_sh_to": "works",
//     "pristine_sigmatism": false,
//     "hissing_nasal_sigmatism": true,
//     "hissing_sigmatism_two": true,
//     "lateral_sigmatism_two": true,
//     "labiodental_pronunciation_of_sibilants": true,
//     "skip_whistling_sound_two": false,
//     "mixing_sounds_two": true,
//     "verbal_memory": "достаточный для полнооценной коммуникации ",
//     "verbal_memory_part_two": "наблюдаются выраженные трудности актуализации слов, хранения и воспроизведения вербальной информации",
//     "expert_comment": "works"
//   },
//   "game_giraffe": {
//     "id": "c161ad68-2c61-4dd6-9762-84e505d710f3",
//     "fish_cow_fence_crab": "works",
//     "river_jam_door": "works",
//     "lamp_milk_floor_treasure": "works",
//     "wheel_salt": "works",
//     "throat_rotacism": true,
//     "replacing_p_with": "works",
//     "replacing_p_soft_with": "works",
//     "buccal": true,
//     "side": true,
//     "one_hit_pronunciation": true,
//     "skip": true,
//     "interdental_lambdacism": true,
//     "replacing_l_with": "works",
//     "replacing_l_soft_with": "works",
//     "nasal": true,
//     "lambdacism_pass": true,
//     "two_lipped": true,
//     "distortion": true,
//     "thinking": "соответствует возрасту",
//     "thinking_part_two": "не нарушено",
//     "there_are_difficulties_in_protecting_adequate_connections": true,
//     "kind_of_thinking": "словесно-логическое, способен давайть своим действиям логическое объяснение",
//     "expert_comment": "works"
//   },
//   "game_puzzle": {
//     "id": "a7362105-f172-45e9-a3ae-308ab71d5478",
//     "wolf_scoop_fork_scroll": "works",
//     "beans_dates": "works",
//     "waffles": "works",
//     "nasal": true,
//     "skip": true,
//     "replacing_with_b": "works",
//     "replacing_with_b_soft": "works",
//     "replacing_with_f": "works",
//     "replacing_with_f_soft": "works",
//     "two_lipped": true,
//     "mixing": true,
//     "distortion": true,
//     "perception": "нарушено",
//     "level_of_perception": "уровень не восприятия соответствует возрасту",
//     "expert_comment": "works"
//   },
//   "game_ant_lambada": {
//     "id": "d4100bc1-e81c-40f7-9d07-391ce182915f",
//     "woodpecker_house": "works",
//     "slipper_dress": "works",
//     "kitchen_hamster_goose": "works",
//     "nasal": true,
//     "skip": true,
//     "replacing_d_with": "works",
//     "replacing_d_soft_with": "works",
//     "replacing_t_with": "works",
//     "replacing_t_soft_with": "works",
//     "replacing_k_with": "works",
//     "replacing_g_with": "works",
//     "replacing_kh_with": "works",
//     "mixing": true,
//     "distortion": true,
//     "expert_comment": "works"
//   },
//   "game_ant_battle": {
//     "id": "53ce1090-5acc-4380-a421-fbf572527c62",
//     "fence": "works",
//     "spatula": "works",
//     "needle": "works",
//     "watch": "works",
//     "swing": "works",
//     "tone": "спастичность мышц языка",
//     "deviation_of_the_tongue": true,
//     "hyperkinesis_of_the_tongue": true,
//     "tremor_of_the_tongue": true,
//     "switching_difficulties": true,
//     "pace_of_the_movements": null,
//     "expert_comment": "works",
//     "raise_eyebrows": "works",
//     "frown": "works",
//     "wink": "works",
//     "puff_out_cheeks": "works",
//     "facial_muscle_tone": "гипотония",
//     "hypomimia": true,
//     "smoothness_of_nasolabial_fold": true,
//     "asymmetry_of_face": true,
//     "facial_hyperkinesis": true,
//     "synkinesis": true,
//     "lip_muscle_tone": "дистония",
//     "restriction_of_lip_mobility": true,
//     "hypersalivation": "после функциональной нагрузки",
//     "static_praxis_stand_on_one_leg_over_the_other": "works",
//     "static_praxis_get_up_on_tiptoe_wait": "works",
//     "dynamic_praxis_jump_on_one_leg_the_other_two": "works",
//     "dynamic_praxis_jump_on_one_leg_the_other_two_part_two": null,
//     "spatial_praxis_turn_right_left": "works",
//     "show_v": "works",
//     "show_the_cow": "works",
//     "show_the_bunny_the_cow_is_counted": "works",
//     "basic_motor_skills": "сформированы недостаточно",
//     "basic_motor_skills_part_two": "соответствуют возрасту",
//     "disturbances_in_tone": "спастичность",
//     "decrease_in_strength": true,
//     "impaired_coordination_of_movement_ataxia": true,
//     "hand_coordination_crashes": true,
//     "motor_shifting_difficulties": true,
//     "body_schema_disorders": true,
//     "disorders_of_hand_eye_coordination": true,
//     "orolingual": true,
//     "opto_lingual": true,
//     "motor_functions_of_hands_and_fingers": "пальцевый праксис сформирован не воспроизвел",
//     "lips": "полные губы",
//     "malocclusion": "перекрестный прикус",
//     "incorrect_position_of_teeth": "сверхкомплектные зубы",
//     "tooth_reshaping": "микродентия",
//     "changing_size_of_tongue": "микроглоссия",
//     "deviation_of_tongue": "вправо",
//     "split_tongue": true,
//     "shortened_hyoid_fold": true,
//     "anomalies_of_frenum_of_upper_lower_lip": "увеличение",
//     "cleft": "скрытая",
//     "gothic_palate": true,
//     "jaw_deformities": true,
//     "pace_of_movement": null
//   },
//   "game_magic_exam": {
//     "id": "4616d921-9fff-48d0-92bb-30e7495b3373",
//     "bear_bowl": "works",
//     "cancer_varnish": "works",
//     "scythe_goat": "works",
//     "duck_fishing_rod": "works",
//     "barrel_kidney": "works",
//     "saber_heron": "works",
//     "level_of_formation_of_phonetic_phonological_competence": "уровень сформированности фонетико-фонологической компетенции соответствует возрастной норме",
//     "state_of_phonemic_perception": "фонематическое восприятие сформировано",
//     "there_are_difficulties_in_distinguishing": true,
//     "distinction_between_hard_and_soft_consonants": true,
//     "distinction_between_affricates_and_their_constituent": true,
//     "expert_comment": "works",
//     "nose": "works",
//     "poppy": "works",
//     "fly": "works",
//     "cats": "works",
//     "what_is_first_sound_in_words_poppy_and_fly": "works",
//     "what_is_first_sound_in_word_nose": "works",
//     "what_is_last_sound_in_words_cat_and_fly": "works",
//     "what_is_last_sound_in_word_poppy": "works",
//     "what_is_common_sound_in_words_of_a_cat_and_anose": "works",
//     "in_which_of_words_there_is_no_sound_about_nose_of_cat_poppy": "works",
//     "phonemic_hearing": "не сформирован",
//     "phonological_sound_analysis_and_synthesis_skills": {
//       "type": ""
//     },
//     "phonemic_hearing_expert_comment": "works"
//   },
//   "game_capricious_princess": {
//     "id": "4742bd59-608d-444c-bb9d-89ad1dd199d9",
//     "chair": "works",
//     "bow": "works",
//     "helicopter": "works",
//     "paper_airplane": "works",
//     "excavator": "works",
//     "camera": "works",
//     "syllabic_structure_of_a_word": "слоговая структура слова не нарушена",
//     "missing_syllables": true,
//     "missing_syllabic_vowels": true,
//     "permutations_of_sounds_and_or_syllables": true,
//     "insertion_of_vowels_into_consonants": true,
//     "adding_syllables": true,
//     "consonant_reduction": true,
//     "inserting_consonants_into_a_syllable": true,
//     "anticipation": true,
//     "assimilation_of_syllables": true,
//     "gnotic_violations_addition_of_syllables": true,
//     "expert_comment": "works"
//   },
//   "attention": {
//     "id": "8975be00-4ad7-4c9a-a0cc-4ed80d0fb165",
//     "speech_attention": null,
//     "there_are_difficulties_in_distributing_attention": null,
//     "low_concentration_and_instability_of_attention": null,
//     "attention_is_unstable_superficial_child_is_very_quickly_depleted": null,
//     "difficulty_concentrating_voluntary_attention": null,
//     "attention_is_not_sustained_enough": null,
//     "sustained_attention": null,
//     "extremely_low_cognitive_activity_and_motivation": null,
//     "low_cognitive_activity_and_motivation_unmotivated": null,
//     "there_is_some_lack_of_cognitive_activity_motivation": null,
//     "pronounced_cognitive_activity_and_motivation": null
//   },
//   "game_how_the_mouse_could_not_sleep": {
//     "id": "f9b80c2e-af8a-4cf1-9dc6-b1fa62d1751b",
//     "mouse_in_the_yard_at_night": false,
//     "mouse_is_eating_an_apple_and_a_berry": false,
//     "moon_in_the_reflection_of_the_water_in_a_puddle": false,
//     "mouse_covers_the_puddle_with_burdock": false,
//     "sun_in_water_reflection_in_a_puddle": false,
//     "what_was_the_white_glowing_circle": "works",
//     "when_did_the_mouse_go_for_a_walk": "works",
//     "what_did_the_mouse_see_in_the_forest": "works",
//     "what_did_the_mouse_cover_the_moon_with": "works",
//     "what_did_the_mouse_see_in_the_puddle_in_the_morning": "works",
//     "why_instead_of_the_moon_the_mouse_found_the_sun": "works",
//     "repeat_the_whole_story_as_you_remember": null,
//     "constructing_a_statement": "не может построить собственное высказывание на основе полученной визуально информации",
//     "consistency_with_the_plot": "рассказ не соответствует предложенному сюжету",
//     "topic": "не раскрыто",
//     "chronological_event_logic": "не соблюдает",
//     "language_means": "неадекватно использует языковые средства при построении связного текста",
//     "phrasal_perseverations": true,
//     "retelling_corresponds_to_original": true,
//     "retelling_contains_both_basic_and_additional_information": true,
//     "retelling_uses_variability_of_speech": true,
//     "retelling_partially_corresponds_to_original": true,
//     "retelling_contains_only_basic_information": true,
//     "vocabulary_and_syntactic_constructions_of_original": true,
//     "coherence_and_consistency_of_presentation_is_not_broken": true,
//     "retelling_does_not_correspond_to_original": null,
//     "semantic_organization_of_text_is_broken": null,
//     "coherence_and_consistency_of_presentation_is_broken": null,
//     "significant_difficulties_in_language_design_of_text": null,
//     "content_semantic_meaning_of_text": "идентифицирует",
//     "understands_only_basic_information_of_text": "доступно понимание как основной, так и дополнительной информации каждой смысловой части текста",
//     "expert_comment": "works",
//     "crepeat_the_whole_story_as_you_remember": "",
//     "has_notable_difficulty_in_story_reproductionretelling_does_not_correspond_to_original": false,
//     "has_notable_difficulty_in_story_reproductionsemantic_organization_of_text_is_broken": false,
//     "has_notable_difficulty_in_story_reproductioncoherence_and_consistency_of_presentation_is_broken": false,
//     "has_notable_difficulty_in_story_reproductionsignificant_difficulties_in_language_design_of_text": false
//   },
//   "game_on_the_farm": {
//     "id": "274a5000-85eb-4565-9eb8-a51fad2016e5",
//     "sandals_boots_socks_boots": "works",
//     "shoes_clothes": "works",
//     "carrot_apple_onion_cabbage": "works",
//     "vegetables_fruits": "works",
//     "table_chair_glass_sofa": "works",
//     "furniture_dishes": "works",
//     "fur_coat_jacket_coat_hat": "works",
//     "clothes_headwear": "works",
//     "doll_cubes_car_trolley": "works",
//     "toys_transport": "works",
//     "cat_kitten": "works",
//     "dog_puppy": "works",
//     "cow_calf": "works",
//     "pig_piglet": "works",
//     "cat_meows": "works",
//     "dog_barks": "works",
//     "cow_hums": "works",
//     "pig_grunts": "works",
//     "low_high_home": "works",
//     "wide_narrow_belt": "works",
//     "heavy_light_bucket_of_water_ball": "works",
//     "clean_dirty_pig": "works",
//     "slow_fast_snail": "works",
//     "sad_cheerful_puppy": "works",
//     "dry_wet_grasshopper": "works",
//     "cold_hot_ice_cream_potatoes": "works",
//     "speech_comprehension_level": "расчлененный",
//     "presence_of_phenomenon_of_alienation": true,
//     "level_of_vocabulary_formation": "не соответствует возрастной норме",
//     "active_semantic_component_active_vocabulary": "наличие неологизмов",
//     "subject_relation_of_a_word": "неустойчивая",
//     "verbal_paraphasias": "вербальные - смешение по внешнему сходству",
//     "vocabulary_size": "достаточный для осуществления полноценной коммуникации",
//     "vocabulary_size_part_two": "очень мало периферийных слов даже из наиболее распространенных, прагматически ценных для этого возраста тематических групп",
//     "systemic_vocabulary_organization": "системная организация словаря отличается большим количеством и разнообразием смысловых и формальных связей; в лексиконе преобладают слова, значение которых усвоено на понятийном уровне",
//     "expert_comment": "works",
//     "to_be_changed": ""
//   },
//   "game_on_the_farm_part_two": {
//     "id": "21286cfd-aecc-4906-9007-2418f5bc4b59",
//     "house": "works",
//     "bucket": "works",
//     "tree": "works",
//     "at_home": "works",
//     "behind_a_tree": "works",
//     "on_the_roof": "works",
//     "to_the_right_of_the_kennel": "works",
//     "on_the_branch_above_misha": "works",
//     "to_the_left_of_the_tree": "works",
//     "under_the_boot": "works",
//     "peeps_out_from_behind_Misha": "works",
//     "in_front_of_the_trough": "works",
//     "misha_has_a_hood": "works",
//     "level_of_grammatical_competence_formation": "значительно ниже возрастной нормы",
//     "inflectional_skills_and_abilities_part_one": "словоизменительные навыки и умения сформированы",
//     "inflectional_skills_and_abilities_part_two": "синтаксические навыки и умения сформированы, в речи наблюдаются многообразие синтаксических конструкций, вариативность их применения, ребенок демонстрирует трансформационные возможности при оперировании синтаксическим материалом",
//     "word_building_skills_and_abilities": "словообразовательная деятельность сформирована",
//     "syntax_skills_and_abilities_part_two": null,
//     "expert_comment": "works"
//   },
//   "game_on_the_farm_part_three": {
//     "id": "897819e4-21dc-4f83-8004-ce9f9a5ed92a",
//     "one_white_chicken": "works",
//     "three_ginger_hens": "works",
//     "five_speckled_hens": "works",
//     "options_for_confinement": "ребенок делает ошибки внутри одного падежа",
//     "expert_comment": "works",
//     "speech_comprehension": null,
//     "there_are_difficulties_in_distributing_attention": true,
//     "concentration": "наблюдаются трудности концентрации произвольного внимания",
//     "sustainability": "внимание устойчивое",
//     "child_s_attention_is_characterized_by_rapid_exhaustion": true,
//     "volume": null,
//     "switchability": null,
//     "fatigue": null,
//     "contact": null,
//     "working_capacity": null,
//     "motivation": null,
//     "interest": null,
//     "options_for_confinement_psychological_basis": "ярко выраженная познавательная активность и мотивация к предметной, предметно-игровой деятельности",
//     "voice": "нормальный",
//     "voice_part_two": "звонкий",
//     "voice_part_three": "тихий",
//     "voice_part_four": "очень низкий",
//     "voice_part_five": "слабо модулированный",
//     "nasalized_voice": true,
//     "smoothness": "речь неплавная",
//     "pace": "патологически замедленный",
//     "speech": "иссякает к концу фразы",
//     "breath": "смешанное",
//     "exhalation": "выдох плавный",
//     "hindered": true,
//     "superficial": true,
//     "breathing_is_not_rhythmic": null,
//     "shallow_breath": true,
//     "rhythm": "нарушен: речь растянутая, скандированная",
//     "expiratory_force": "сильная",
//     "inspiratory_expiratory_differentiation": "нарушена",
//     "prosodic_side_of_speech": "речь внятная, понятная для окружающих",
//     "speech_intonationally": "речь интонационно невыразительна: слабая выраженность голосовых модуляций",
//     "violation_of_tempo_rhythmic_organization_of_speech": "запинки",
//     "speech_comprehensionthere_are_difficulties_in_distributing_attention": null,
//     "to_be_changed": false
//   },
//   "additional_information": {
//     "id": "66d1a2c7-fa74-4035-9414-f5d8556a3bc5",
//     "sat_in": "works",
//     "crawled_on_all_fours_into": "works",
//     "went_to": "works",
//     "learned_to_jump_on_two_legs_in": null,
//     "injury_infection_before_during_and_or_after_childbirth": "works",
//     "babbling_in": {
//       "babbling_age": ""
//     },
//     "first_words_in": {
//       "first_words_age": ""
//     },
//     "first_short_phrases_in": {
//       "first_short_phrases_age": ""
//     },
//     "speech_environment": "works",
//     "present_and_past_diseases": "works",
//     "drug_treatment": "works",
//     "neurological_status": "works",
//     "vision": "works",
//     "hearing": "works",
//     "eating_behavior": "works",
//     "emotional_and_psychological_level": "works",
//     "speech_therapy_conclusion": "works",
//     "dynamic_conclusion": "works",
//     "final_conclusion": "works",
//     "llearned_to_jump_on_two_legs_in": ""
//   },
//   "child_full_name": null,
//   "child_date_of_birth": null,
//   "what_are_your_complaints": "tests",
//   "for_what_purpose_did_you_turn_to_a_speech_therapist": "works",
//   "what_is_your_name": "works",
//   "how_old_are_you": 13,
//   "what_is_your_moms_name_your_daddy": "works",
//   "where_do_you_live": "works",
//   "what_time_of_year_is_it": "works",
//   "what_did_you_do_yesterday": "works",
//   "what_toys_do_you_have": "works",
//   "what_kind_of_animals_do_you_know": "works",
//   "general_ideas_about_the_world_around_comment": "works",
//   "stock_of_knowledge_about_the_world_around": "запас знаний об окружающем мире крайне низкий",
//   "in_a_time_space_situation": "ориентируется",
//   "knows_how_old_time_of_year_what_time_of_day_it_is": false,
//   "image_i": "сформирован",
//   "knows_his_name_the_name_of_his_parents_where_he_lives": false,
//   "somatognosis_understanding_your_own_body": "сформирован",
//   "contact_with_the_child": true,
//   "formation_of_ideas_about_the_world_around_comment": "works",
//   "leading_ear_phone": "правое ухо",
//   "leading_hand_phone": "правая рука",
//   "leading_hand_spyglass": "левая рука",
//   "leading_eye_spyglass": null,
//   "leading_leg_ball": "правая нога",
//   "conclusion_options": "левшество, все 4 показателя совпадают",
//   "parent": "03f8c308-d681-4a4a-856f-7fc4649ce98a",
//   "child": "2c26bdc8-dee9-4041-a8df-440ff60bcb1d",
//   "lesson": null
// }
