const requiredFields = {
  mimic_manifestations: 'TEST',
  basic_emotions_that_it_exhibits: 'TEST',
  formation_of_skills_of_sound_analysis_and_synthesis: 'TEST',
  general_ideas_of_child_about_world_around_him: 'TEST',
  volume_vocabulary: 'TEST',
  system_organization_of_dictionary_associative_links: 'TEST',
  syllabic_structure_of_word: 'TEST',
  prosodic_speech_design: 'TEST',
  motor_functions_of_articulatory_apparatus: 'TEST',
  oral_praxis: 'TEST',
  articulatory_praxis: 'TEST',
  speech_breathing_and_voice_production: 'TEST',
  postural_control_of_calm_state: 'TEST',
  bilateral_motor_coordination: 'TEST',
  formation_of_motor_imitation: 'TEST',
  speech_attention: 'TEST',
  features_of_early_speech_development: 'TEST',
  features_of_speech_environment_in_which_child: 'TEST',
  features_of_speech_behavior: 'TEST',
  neurological_status_and_condition: 'TEST',
  information_about_current_and_past_diseases: 'TEST',
  emotional_reaction: 'TEST',
  emotional_response_to_adult_emotion: 'TEST',
  in_case_of_failure_behaves: 'TEST',
  logopedic_conclusion: 'TEST',
  recommendation: 'TEST',
};

export default requiredFields;
