variables:
  DEPLOY_USER: "infrastructure"
  DEV_API_URL: "https://dev.yba.ltestl.com/api/v1"
  DEV_WS_URL: "wss://dev.yba.ltestl.com/ws"
  STAGING_API_URL: "https://staging.yba.ltestl.com/api/v1"
  STAGING_WS_URL: "wss://staging.yba.ltestl.com/ws"
  PRODUCTION_API_URL: "https://diagnostika.pro/api/v1"
  PRODUCTION_WS_URL: "wss://diagnostika.pro/ws"

.add-ssh-private-key-script: &add-ssh-private-key
  - apk update
  - apk add -qq
  - 'which ssh-agent || ( apk add -qq openssh-client )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | ssh-add -
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts

.deploy-script: &deploy
  - ssh -T $DEPLOY_USER@$DEPLOY_SERVER "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
  - ssh -T $DEPLOY_USER@$DEPLOY_SERVER "docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  - ssh -T $DEPLOY_USER@$DEPLOY_SERVER "docker rm -f ybba-frontend && docker run -d --network ybba-backend_default --name ybba-frontend -p 3000:80 $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"

services:
  - docker:dind

stages:
  - test
  - build
  - deploy-development
  - deploy-staging
  - deploy-production


test:
  image: docker/compose:latest
  stage: test
  environment:
    name: testing
  only:
    - merge_requests
  script:
    - echo "We need tests!!!"

build&push:
  image: docker:stable
  stage: build
  only:
    refs:
      - development
      - staging
      - main
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - >
      docker build
      -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      --cache-from $CI_REGISTRY_IMAGE:latest
      -f dockerfiles/app/Dockerfile
      --build-arg REACT_APP_API_URL=$DEV_API_URL
      --build-arg REACT_APP_SENTRY_DSN=$REACT_APP_SENTRY_DSN
      --build-arg REACT_APP_ENVIRONMENT=development
      --build-arg REACT_APP_WS_URL=$DEV_WS_URL
      --build-arg REACT_APP_ROBOKASSA_MERCHANT_LOGIN=$ROBOKASSA_MERCHANT_LOGIN
      --build-arg REACT_APP_ROBOKASSA_PASSWORD=$ROBOKASSA_PASSWORD
      .
    - >
      docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

deploy-development:
  image: docker:git
  stage: deploy-development
  environment:
    name: development
    url: https://dev.yba.ltestl.com/
  only:
    refs:
      - development
  variables:
    SSH_PRIVATE_KEY: $DEVELOPMENT_SSH_PRIVATE_KEY
    DEPLOY_SERVER: 139.59.152.145
  before_script:
    - *add-ssh-private-key
  script:
    - *deploy

deploy-staging:
  image: docker:git
  stage: deploy-staging
  when: manual
  environment:
    name: staging
    url: https://staging.yba.ltestl.com/
  variables:
    SSH_PRIVATE_KEY: $STAGING_SSH_PRIVATE_KEY
    DEPLOY_SERVER: 104.248.254.28
  before_script:
    - *add-ssh-private-key
  script:
    - *deploy

deploy-production:
  image: docker:git
  stage: deploy-production
  when: manual
  environment:
    name: production
    url: https://diagnostika.pro/
  variables:
    SSH_PRIVATE_KEY: $PRODUCTION_SSH_PRIVATE_KEY
    DEPLOY_SERVER: 138.68.73.157
  before_script:
    - *add-ssh-private-key
  script:
    - *deploy
