variables:
  DEPLOY_USER: "infrastructure"

.add-ssh-private-key-script: &add-ssh-private-key
  - apk update
  - apk add -qq
  - 'which ssh-agent || ( apk add -qq openssh-client )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | ssh-add -
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts

.deploy-script: &deploy
  - ssh -T $DEPLOY_USER@$DEPLOY_SERVER "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
  - ssh -T $DEPLOY_USER@$DEPLOY_SERVER "docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  - ssh -T $DEPLOY_USER@$DEPLOY_SERVER "docker rm -f ybba-frontend && docker run -d --name ybba-frontend -p 3000:80 $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"

.build-and-push-script: &build-and-push
  - >
    docker build
    -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    --cache-from $CI_REGISTRY_IMAGE:latest
    -f dockerfiles/app/Dockerfile
    --build-arg REACT_APP_SENTRY_DSN=$REACT_APP_SENTRY_DSN
    --build-arg REACT_APP_ENVIRONMENT=$REACT_APP_ENVIRONMENT
    --build-arg REACT_APP_ROBOKASSA_MERCHANT_LOGIN=$REACT_APP_ROBOKASSA_MERCHANT_LOGIN
    --build-arg REACT_APP_ROBOKASSA_PASSWORD=$REACT_APP_ROBOKASSA_PASSWORD
    --build-arg REACT_APP_DROPBOX_TOKEN=$REACT_APP_DROPBOX_TOKEN
    --build-arg REACT_APP_SESSION_STACK_ID=$REACT_APP_SESSION_STACK_ID
    --build-arg REACT_APP_FIREBASE_VAPID_KEY=$REACT_APP_FIREBASE_VAPID_KEY
    .
  - >
    docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

services:
  - docker:dind

stages:
  - test
  - build
  - deploy-development
  - deploy-staging
  - deploy-production


test:
  image: docker/compose:latest
  stage: test
  environment:
    name: testing
  only:
    - merge_requests
  script:
    - echo "We need tests!!!"

build&push_dev:
  image: docker:stable
  stage: build
  only:
    refs:
      - development
  variables:
    REACT_APP_SENTRY_DSN: $REACT_APP_SENTRY_DSN
    REACT_APP_ENVIRONMENT: development
    REACT_APP_ROBOKASSA_MERCHANT_LOGIN: $ROBOKASSA_MERCHANT_LOGIN
    REACT_APP_ROBOKASSA_PASSWORD: $ROBOKASSA_PASSWORD
    REACT_APP_DROPBOX_TOKEN: $REACT_APP_DROPBOX_TOKEN
    REACT_APP_SESSION_STACK_ID: $REACT_APP_SESSION_STACK_ID
    REACT_APP_FIREBASE_VAPID_KEY: $REACT_APP_FIREBASE_VAPID_KEY
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    *build-and-push

build&push_staging:
  image: docker:stable
  stage: build
  only:
    refs:
      - staging
  variables:
    REACT_APP_SENTRY_DSN: $REACT_APP_SENTRY_DSN
    REACT_APP_ENVIRONMENT: staging
    REACT_APP_ROBOKASSA_MERCHANT_LOGIN: $ROBOKASSA_MERCHANT_LOGIN
    REACT_APP_ROBOKASSA_PASSWORD: $ROBOKASSA_PASSWORD
    REACT_APP_DROPBOX_TOKEN: $REACT_APP_DROPBOX_TOKEN
    REACT_APP_SESSION_STACK_ID: $REACT_APP_SESSION_STACK_ID
    REACT_APP_FIREBASE_VAPID_KEY: $REACT_APP_FIREBASE_VAPID_KEY
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    *build-and-push

build&push_prod:
  image: docker:stable
  stage: build
  only:
    refs:
      - main
  variables:
    REACT_APP_SENTRY_DSN: $REACT_APP_SENTRY_DSN
    REACT_APP_ENVIRONMENT: production
    REACT_APP_ROBOKASSA_MERCHANT_LOGIN: $ROBOKASSA_MERCHANT_LOGIN
    REACT_APP_ROBOKASSA_PASSWORD: $ROBOKASSA_PASSWORD
    REACT_APP_DROPBOX_TOKEN: $REACT_APP_DROPBOX_TOKEN
    REACT_APP_SESSION_STACK_ID: $REACT_APP_SESSION_STACK_ID
    REACT_APP_FIREBASE_VAPID_KEY: $REACT_APP_FIREBASE_VAPID_KEY
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    *build-and-push

deploy-development:
  image: docker:git
  stage: deploy-development
  environment:
    name: development
    url: https://dev.yba.ltestl.com/
  only:
    refs:
      - development
  variables:
    SSH_PRIVATE_KEY: $DEVELOPMENT_SSH_PRIVATE_KEY
    DEPLOY_SERVER: 139.59.152.145
  before_script:
    - *add-ssh-private-key
  script:
    - *deploy

deploy-staging:
  image: docker:git
  stage: deploy-staging
  when: manual
  environment:
    name: staging
    url: https://staging.yba.ltestl.com/
  only:
    refs:
      - staging
  variables:
    SSH_PRIVATE_KEY: $STAGING_SSH_PRIVATE_KEY
    DEPLOY_SERVER: 104.248.254.28
  before_script:
    - *add-ssh-private-key
  script:
    - *deploy

deploy-production:
  image: docker:git
  stage: deploy-production
  when: manual
  environment:
    name: production
    url: https://diagnostika.pro/
  only:
    refs:
      - main
  variables:
    SSH_PRIVATE_KEY: $PRODUCTION_SSH_PRIVATE_KEY
    DEPLOY_SERVER: 207.154.202.69
  before_script:
    - *add-ssh-private-key
  script:
    - *deploy
