import React from 'react';
import { useTranslation } from 'react-i18next';

import ProtocolPlaceholderTitle from 'Components/Surveys/ExaminationProtocol/ProtocolPlaceholderTitle/ProtocolPlaceholderTitle';
import ProtocolBlockTitle from 'Components/Surveys/ExaminationProtocol/ProtocolBlockTitle/ProtocolBlockTitle';
import ProtocolBlock from 'Components/Surveys/ExaminationProtocol/ProtocolBlock/ProtocolBlock';
import ProtocolFormField from 'Components/Surveys/ExaminationProtocol/ProtocolFormField/ProtocolFormField';
import ProtocolRow from 'Components/Surveys/ExaminationProtocol/ProtocolRow/ProtocolRow';
import ProtocolBox from 'Components/Surveys/ExaminationProtocol/ProtocolBox/ProtocolBox';
import ProtocolBoxTitle from 'Components/Surveys/ExaminationProtocol/ProtocolBoxTitle/ProtocolBoxTitle';
import ProtocolResultTitle from 'Components/Surveys/ExaminationProtocol/ResultTitle/ResultTitle';
import ProtocolDescriptionSubtitle from 'Components/Surveys/ExaminationProtocol/ProtocolResultTitle/ProtocolResultTitle';
import ProtocolResultBlock from 'Components/Surveys/ExaminationProtocol/ProtocolResultBlock/ProtocolResultBlock';
import ProtocolResultWrapper from 'Components/Surveys/ExaminationProtocol/ProtocolResultWrapper/ProtocolResultWrapper';
import ProtocolTitle from 'Components/Surveys/ExaminationProtocol/ProtocolTitle/ProtocolTitle';
import ProtocolDescriptionMain from 'Components/Surveys/ExaminationProtocol/ProtocolDescriptionMain/ProtocolDescriptionMain';


const AntBattleGame = (props) => {

    const {
        register, errors, control, disabled
    } = props

    const { t } = useTranslation();

    return (
        <>
            <ProtocolBlock>
                <ProtocolPlaceholderTitle>{t('ant_battle_game')}</ProtocolPlaceholderTitle>
                <ProtocolBlockTitle>{t('the_state_of_the_articulatory_apparatus_and_motor_development')}</ProtocolBlockTitle>
                <p className='protocol__subtitle-block'>{t('articulatory_motility')}</p>
                <p className='protocol__sub2title-block'>{t('praxis')}</p>
                <ProtocolBox>
                    <ProtocolBoxTitle>{t('static_praxis')}</ProtocolBoxTitle>
                    <ProtocolRow>
                        <ProtocolFormField
                            type='text'
                            label={t('fence')}
                            name='game_ant_battle.fence'
                            register={register}
                            errors={errors}
                            disabled={disabled}
                        />
                    </ProtocolRow>
                    <ProtocolRow>
                        <ProtocolFormField
                            type='text'
                            label={t('shoulder')}
                            name='game_ant_battle.spatula'
                            register={register}
                            errors={errors}
                            disabled={disabled}
                        />
                    </ProtocolRow>
                    <ProtocolRow>
                        <ProtocolFormField
                            type='text'
                            label={t('needle')}
                            name='game_ant_battle.needle'
                            register={register}
                            errors={errors}
                            disabled={disabled}
                        />
                    </ProtocolRow>
                    <ProtocolRow>
                        <ProtocolFormField
                            type='text'
                            label={t('mushroom')}
                            name='game_ant_battle.mushroom'
                            register={register}
                            errors={errors}
                            disabled={disabled}
                        />
                    </ProtocolRow>
                    <ProtocolRow>
                        <ProtocolFormField
                            type='text'
                            label={t('birdie')}
                            name='game_ant_battle.window'
                            register={register}
                            errors={errors}
                            disabled={disabled}
                        />
                    </ProtocolRow>
                </ProtocolBox>
                <ProtocolBox>
                    <ProtocolBoxTitle>{t('dynamic_praxis')}</ProtocolBoxTitle>
                    <ProtocolRow>
                        <ProtocolFormField
                            type='text'
                            label={t('an_hour')}
                            name='game_ant_battle.watch'
                            register={register}
                            errors={errors}
                            disabled={disabled}
                        />
                    </ProtocolRow>
                    <ProtocolRow>
                        <ProtocolFormField
                            type='text'
                            label={t('swing')}
                            name='game_ant_battle.swing'
                            register={register}
                            errors={errors}
                            disabled={disabled}
                        />
                    </ProtocolRow>
                    <ProtocolRow>
                        <ProtocolFormField
                            type='text'
                            label={t('the_horse')}
                            name='game_ant_battle.horse'
                            register={register}
                            errors={errors}
                            disabled={disabled}
                        />
                    </ProtocolRow>
                </ProtocolBox>
                <ProtocolResultTitle>{t('conclusion_options')}</ProtocolResultTitle>
                <ProtocolRow>
                    <ProtocolDescriptionSubtitle>{t('tone')}</ProtocolDescriptionSubtitle>
                    <ProtocolResultBlock>
                        <ProtocolFormField
                            type='radio'
                            label={t('spasticity_of_the_muscles_of_the_tongue')}
                            name='game_ant_battle.tone'
                            control={control}
                            errors={errors}
                            disabled={disabled}
                        />
                    </ProtocolResultBlock>
                    <ProtocolResultBlock>
                        <ProtocolFormField
                            type='radio'
                            label={t('hypotonia_of the muscles of the tongue')}
                            name='game_ant_battle.tone'
                            control={control}
                            errors={errors}
                            disabled={disabled}
                        />
                    </ProtocolResultBlock>
                    <ProtocolResultBlock>
                        <ProtocolFormField
                            type='radio'
                            label={t('dystonia_of_tongue_muscles')}
                            name='game_ant_battle.tone'
                            control={control}
                            errors={errors}
                            disabled={disabled}
                        />
                    </ProtocolResultBlock>
                    <ProtocolResultBlock>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='checkbox'
                                label={t('deviation_of_the_tongue_deviations_of_the_tongue_to_the_side')}
                                name='game_ant_battle.deviation_of_the_tongue'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='checkbox'
                                label={t('hyperkinesis_of_the_tongue')}
                                name='game_ant_battle.hyperkinesis_of_the_tongue'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='checkbox'
                                label={t('tremor_of_the_tongue')}
                                name='game_ant_battle.tremor_of_the_tongue'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='checkbox'
                                label={t('switching_difficulties')}
                                name='game_ant_battle.switching_difficulties'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        {errors.choices6 && <div className='form2__error'> {errors.choices6.message}</div>}
                    </ProtocolResultBlock>
                </ProtocolRow>
                <ProtocolRow>
                    <ProtocolDescriptionSubtitle>{t('movement_pace')}</ProtocolDescriptionSubtitle>
                    <ProtocolResultBlock>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('slow_pace_of_movement')}
                                name='game_ant_battle.pace_of_the_movements'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('accelerated_pace_of_movement')}
                                name='game_ant_battle.pace_of_the_movements'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                    </ProtocolResultBlock>
                </ProtocolRow>
                <ProtocolRow>
                    <ProtocolFormField
                        type='textarea'
                        label={t('comment')}
                        name='game_ant_battle.expert_comment'
                        placeholder={t('expert_comment')}
                        errors={errors}
                        register={register}
                        disabled={disabled}
                    />
                </ProtocolRow>
            </ProtocolBlock>
            <ProtocolBlock>
                <ProtocolBlockTitle>{t('mimic_muscles')} <span>{t('exercise')}</span></ProtocolBlockTitle>
                <ProtocolRow>
                    <ProtocolFormField
                        type='text'
                        label={t('raise_your_eyebrows')}
                        name='game_ant_battle.raise_eyebrows'
                        register={register}
                        errors={errors}
                        disabled={disabled}
                    />
                </ProtocolRow>
                <ProtocolRow>
                    <ProtocolFormField
                        type='text'
                        label={t('furrow_your_brows')}
                        name='game_ant_battle.frown'
                        register={register}
                        errors={errors}
                        disabled={disabled}
                    />
                </ProtocolRow>
                <ProtocolRow>
                    <ProtocolFormField
                        type='text'
                        label={t('wink')}
                        name='game_ant_battle.wink'
                        register={register}
                        errors={errors}
                        disabled={disabled}
                    />
                </ProtocolRow>
                <ProtocolRow>
                    <ProtocolFormField
                        type='text'
                        label={t('puff_out_cheeks')}
                        name='game_ant_battle.puff_out_cheeks'
                        register={register}
                        errors={errors}
                        disabled={disabled}
                    />
                </ProtocolRow>
                <ProtocolResultTitle>{t('conclusion_options')}</ProtocolResultTitle>
                <ProtocolRow>
                    <ProtocolDescriptionSubtitle>{t('facial_muscle_tone')}</ProtocolDescriptionSubtitle>
                    <ProtocolResultBlock>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('spasticity')}
                                name='game_ant_battle.facial_muscle_tone'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('hypotension')}
                                name='game_ant_battle.facial_muscle_tone'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('dystonia')}
                                name='game_ant_battle.facial_muscle_tone'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                    </ProtocolResultBlock>
                    <ProtocolResultBlock>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='checkbox'
                                label={t('hypomimia')}
                                name='game_ant_battle.hypomimia'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='checkbox'
                                label={t('flattening_of_the_nasolabial_fold')}
                                name='game_ant_battle.smoothness_of_nasolabial_fold'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='checkbox'
                                label={t('facial_asymmetry')}
                                name='game_ant_battle.asymmetry_of_face'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='checkbox'
                                label={t('hyperkinesis_of_the_face')}
                                name='game_ant_battle.facial_hyperkinesis'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='checkbox'
                                label={t('synkinesia')}
                                name='game_ant_battle.synkinesis'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        {errors.choices7 && <div className='form2__error'> {errors.choices7.message}</div>}
                    </ProtocolResultBlock>
                </ProtocolRow>
                <ProtocolRow>
                    <ProtocolResultTitle>{t('lip_muscle_tone')}</ProtocolResultTitle>
                    <ProtocolResultBlock>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('spasticity')}
                                name='game_ant_battle.lip_muscle_tone'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('hypotension')}
                                name='game_ant_battle.lip_muscle_tone'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('dystonia')}
                                name='game_ant_battle.lip_muscle_tone'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='checkbox'
                                label={t('lip_restriction')}
                                name='game_ant_battle.restriction_of_lip_mobility'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                    </ProtocolResultBlock>
                </ProtocolRow>
                <ProtocolRow>
                    <ProtocolResultTitle>{t('hypersalivation')}</ProtocolResultTitle>
                    <ProtocolResultWrapper>
                        <ProtocolFormField
                            type='radio'
                            label={t('constant')}
                            name='game_ant_battle.hypersalivation'
                            control={control}
                            errors={errors}
                            disabled={disabled}
                        />
                    </ProtocolResultWrapper>
                    <ProtocolResultWrapper>
                        <ProtocolFormField
                            type='radio'
                            label={t('after_functional_loading')}
                            name='game_ant_battle.hypersalivation'
                            control={control}
                            errors={errors}
                            disabled={disabled}
                        />
                    </ProtocolResultWrapper>
                </ProtocolRow>
            </ProtocolBlock>
            <ProtocolBlock>
                <ProtocolTitle>{t('general_and_fine_motor_skills')}</ProtocolTitle>
                <ProtocolBlockTitle>{t('praxis')}</ProtocolBlockTitle>
                <ProtocolBox>
                    <p className='protocol__sub2title-block'>{t('static_praxis')}</p>
                    <ProtocolRow>
                        <ProtocolFormField
                            type='text'
                            label={t('stand_on_one_leg_on_the_other_count_up_to_4x')}
                            name='game_ant_battle.static_praxis_stand_on_one_leg_over_the_other'
                            register={register}
                            errors={errors}
                            disabled={disabled}
                        />
                    </ProtocolRow>
                    <ProtocolRow>
                        <ProtocolFormField
                            type='text'
                            label={t('get_up_on_your_tiptoes_wait_count_up_to_4x')}
                            name='game_ant_battle.static_praxis_get_up_on_tiptoe_wait'
                            register={register}
                            errors={errors}
                            disabled={disabled}
                        />
                    </ProtocolRow>
                </ProtocolBox>
                <ProtocolBox>
                    <ProtocolBoxTitle>{t('dynamic_praxis')}</ProtocolBoxTitle>
                    <ProtocolFormField
                        type='text'
                        label={t('jump_on_one_leg_the_other_two_count_up_to_5_on_each_leg')}
                        name='game_ant_battle.dynamic_praxis_jump_on_one_leg_the_other_two'
                        register={register}
                        errors={errors}
                        disabled={disabled}
                    />
                </ProtocolBox>
                <ProtocolBox>
                    <ProtocolBoxTitle>{t('spatial_praxis')}</ProtocolBoxTitle>
                    <ProtocolFormField
                        type='text'
                        label={t('turn_right_turn_left')}
                        name='game_ant_battle.spatial_praxis_turn_right_left'
                        register={register}
                        errors={errors}
                        disabled={disabled}
                    />
                </ProtocolBox>
                <p className='protocol__sub2title-block'>{t('finger_praxis')}</p>
                <ProtocolBox>
                    <ProtocolBoxTitle>{t('with_tactic_praxis')}</ProtocolBoxTitle>
                    <ProtocolFormField
                        type='text'
                        label={t('show_V_bunny')}
                        name='game_ant_battle.show_v'
                        register={register}
                        errors={errors}
                        disabled={disabled}
                    />
                    <ProtocolFormField
                        type='text'
                        label={t('show_the_cow')}
                        name='game_ant_battle.show_the_cow'
                        register={register}
                        errors={errors}
                        disabled={disabled}
                    />
                </ProtocolBox>
                <ProtocolBox>
                    <ProtocolBoxTitle>{t('dynamic_praxis')}</ProtocolBoxTitle>
                    <ProtocolFormField
                        type='text'
                        label={t('show_bunny_cow_under_the_account')}
                        name='game_ant_battle.show_the_bunny_the_cow_is_counted'
                        register={register}
                        errors={errors}
                        disabled={disabled}
                    />
                </ProtocolBox>
                <ProtocolResultTitle>{t('conclusion_options')}</ProtocolResultTitle>
                <ProtocolRow>
                    <ProtocolDescriptionSubtitle>{t('basic_motor_skills')}</ProtocolDescriptionSubtitle>
                    <ProtocolResultBlock>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('formed')}
                                name='game_ant_battle.basic_motor_skills'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('not_formed_enough')}
                                name='game_ant_battle.basic_motor_skills'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('not_formed')}
                                name='game_ant_battle.basic_motor_skills'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                    </ProtocolResultBlock>
                    <ProtocolResultBlock>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('age_appropriate')}
                                name='game_ant_battle.basic_motor_skills_part_two'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('not_age_appropriate')}
                                name='game_ant_battle.basic_motor_skills_part_two'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                    </ProtocolResultBlock>
                </ProtocolRow>
                <ProtocolRow>
                    <ProtocolDescriptionMain>{t('violations_of_primary_motor_function')}</ProtocolDescriptionMain>
                    <ProtocolDescriptionSubtitle>{t('violations_of_tone')}</ProtocolDescriptionSubtitle>
                    <ProtocolResultBlock>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('spasticity')}
                                name='game_ant_battle.disturbances_in_tone'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('hypotension')}
                                name='game_ant_battle.disturbances_in_tone'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('dystonia')}
                                name='game_ant_battle.disturbances_in_tone'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                    </ProtocolResultBlock>
                    <ProtocolResultBlock>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='checkbox'
                                label={t('decrease_in_strength')}
                                name='game_ant_battle.decrease_in_strength'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='checkbox'
                                label={t('movement_disorders_ataxia')}
                                name='game_ant_battle.impaired_coordination_of_movement_ataxia'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='checkbox'
                                label={t('violations_of_the_coordination_of_actions_of_the_hands')}
                                name='game_ant_battle.hand_coordination_crashes'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='checkbox'
                                label={t('motor_switching_difficulties')}
                                name='game_ant_battle.motor_shifting_difficulties'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        {errors.choices8 && <div className='form2__error'> {errors.choices8.message}</div>}
                    </ProtocolResultBlock>
                </ProtocolRow>
                <ProtocolRow>
                    <ProtocolDescriptionSubtitle>{t('violations_of_certain_aspects_of_sensorimotor_function')}</ProtocolDescriptionSubtitle>
                    <ProtocolResultBlock>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='checkbox'
                                label={t('body_schema_disorders')}
                                name='game_ant_battle.body_schema_disorders'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='checkbox'
                                label={t('violations_of_hand_eye_coordination')}
                                name='game_ant_battle.disorders_of_hand_eye_coordination'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        {errors.choices9 && <div className='form2__error'> {errors.choices9.message}</div>}
                    </ProtocolResultBlock>
                </ProtocolRow>
                <ProtocolRow>
                    <ProtocolDescriptionSubtitle>{t('friendly_movements_synkinesias')}</ProtocolDescriptionSubtitle>
                    <ProtocolResultBlock>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='checkbox'
                                label={t('orolingual')}
                                name='game_ant_battle.orolingual'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='checkbox'
                                label={t('optolingual')}
                                name='game_ant_battle.opto_lingual'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        {errors.choices10 && <div className='form2__error'> {errors.choices10.message}</div>}
                    </ProtocolResultBlock>
                </ProtocolRow>
                <ProtocolRow>
                    <ProtocolDescriptionSubtitle>{t('motor_functions_of_the_hands_and_fingers')}</ProtocolDescriptionSubtitle>
                    <ProtocolResultBlock>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('finger_praxis_formed_reproduced_the_finger_pose_without_difficulty')}
                                name='game_ant_battle.motor_functions_of_hands_and_fingers'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('finger_praxis_formed_reproduced_finger_posture_with_difficulty')}
                                name='game_ant_battle.motor_functions_of_hands_and_fingers'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('finger_praxis_is_not_formed_did_not_reproduce_the_finger_pose')}
                                name='game_ant_battle.motor_functions_of_hands_and_fingers'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                    </ProtocolResultBlock>
                </ProtocolRow>
            </ProtocolBlock>
            <ProtocolBlock>
                <ProtocolTitle>{t('the_structure_of_the_articulatory_apparatus')}</ProtocolTitle>
                <ProtocolResultTitle>{t('conclusion_options')}</ProtocolResultTitle>
                <ProtocolRow>
                    <ProtocolDescriptionSubtitle>{t('lips')}</ProtocolDescriptionSubtitle>
                    <ProtocolResultBlock>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('thin')}
                                value={t('thin_lips')}
                                name='game_ant_battle.lips'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('full')}
                                value={t('full_lips')}
                                name='game_ant_battle.lips'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='checkbox'
                                label={t('lingering_lips')}
                                name='game_ant_battle.non_closure_of_lips'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                    </ProtocolResultBlock>
                    <ProtocolDescriptionMain>{t('tooth_jaw_anomalies')}</ProtocolDescriptionMain>
                    <ProtocolDescriptionSubtitle>{t('eating_disorders')}</ProtocolDescriptionSubtitle>
                    <ProtocolResultBlock>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('prognathia')}
                                name='game_ant_battle.malocclusion'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('progenia')}
                                name='game_ant_battle.malocclusion'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('deep_bite')}
                                name='game_ant_battle.malocclusion'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('open_bite')}
                                name='game_ant_battle.malocclusion'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('crossbite')}
                                name='game_ant_battle.malocclusion'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                    </ProtocolResultBlock>
                    <ProtocolDescriptionSubtitle>{t('misposition_of_teeth')}</ProtocolDescriptionSubtitle>
                    <ProtocolResultBlock>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('adentia')}
                                name='game_ant_battle.incorrect_position_of_teeth'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('diastema')}
                                name='game_ant_battle.incorrect_position_of_teeth'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('supernumerary_teeth')}
                                name='game_ant_battle.incorrect_position_of_teeth'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                    </ProtocolResultBlock>
                    <ProtocolDescriptionSubtitle>{t('changing_the_shape_of_the_teeth')}</ProtocolDescriptionSubtitle>
                    <ProtocolResultBlock>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('macrodentia')}
                                name='game_ant_battle.tooth_reshaping'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('microdentia')}
                                name='game_ant_battle.tooth_reshaping'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                    </ProtocolResultBlock>
                    <ProtocolDescriptionMain>{t('language_anomalies')}</ProtocolDescriptionMain>
                    <ProtocolDescriptionSubtitle>{t('tongue_size_change')}</ProtocolDescriptionSubtitle>
                    <ProtocolResultBlock>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('macroglossia')}
                                name='game_ant_battle.changing_size_of_tongue'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('microglossia')}
                                name='game_ant_battle.changing_size_of_tongue'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                    </ProtocolResultBlock>
                    <ProtocolDescriptionSubtitle>{t('tongue_deviation')}</ProtocolDescriptionSubtitle>
                    <ProtocolResultWrapper>
                        <ProtocolFormField
                            type='radio'
                            label={t('missing')}
                            name='game_ant_battle.deviation_of_tongue'
                            control={control}
                            errors={errors}
                            disabled={disabled}
                        />
                    </ProtocolResultWrapper>
                    <ProtocolResultWrapper>
                        <ProtocolFormField
                            type='radio'
                            label={t('left')}
                            name='game_ant_battle.deviation_of_tongue'
                            control={control}
                            errors={errors}
                            disabled={disabled}
                        />
                    </ProtocolResultWrapper>
                    <ProtocolResultWrapper>
                        <ProtocolFormField
                            type='radio'
                            label={t('right')}
                            name='game_ant_battle.deviation_of_tongue'
                            control={control}
                            errors={errors}
                            disabled={disabled}
                        />
                    </ProtocolResultWrapper>
                    <ProtocolResultBlock>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='checkbox'
                                label={t('forked_tongue')}
                                name='game_ant_battle.split_tongue'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='checkbox'
                                label={t('shortened_hyoid_fold')}
                                name='game_ant_battle.shortened_hyoid_fold'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        {errors.choices11 && <div className='form2__error'> {errors.choices11.message}</div>}
                    </ProtocolResultBlock>
                    <ProtocolDescriptionSubtitle>{t('anomalies_of_the_frenulum_of_the_upper_lower_lip')}</ProtocolDescriptionSubtitle>
                    <ProtocolResultBlock>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('shortening')}
                                name='game_ant_battle.anomalies_of_frenum_of_upper_lower_lip'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('increase')}
                                name='game_ant_battle.anomalies_of_frenum_of_upper_lower_lip'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                    </ProtocolResultBlock>
                    <ProtocolDescriptionMain>{t('malformations_of_the_maxillofacial_region_and_systemic_anomalies_of_the_soft_tissues_and_bones_of_the_face')}</ProtocolDescriptionMain>
                    <ProtocolDescriptionSubtitle>{t('cleft')}</ProtocolDescriptionSubtitle>
                    <ProtocolResultBlock>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('lips')}
                                name='game_ant_battle.cleft'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('hard_and_soft_palate')}
                                name='game_ant_battle.cleft'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('alveolar_process_of_the_palate')}
                                name='game_ant_battle.cleft'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='radio'
                                label={t('hidden')}
                                name='game_ant_battle.cleft'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                    </ProtocolResultBlock>
                    <ProtocolResultBlock>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='checkbox'
                                label={t('gothic_palate')}
                                name='game_ant_battle.gothic_palate'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        <ProtocolResultWrapper>
                            <ProtocolFormField
                                type='checkbox'
                                label={t('jaw_deformities')}
                                name='game_ant_battle.jaw_deformities'
                                control={control}
                                errors={errors}
                                disabled={disabled}
                            />
                        </ProtocolResultWrapper>
                        {errors.choices12 && <div className='form2__error'> {errors.choices12.message}</div>}
                    </ProtocolResultBlock>
                </ProtocolRow>
            </ProtocolBlock>
        </>
    );
};

export default AntBattleGame;