import React from 'react';
import { useTranslation } from 'react-i18next';


import ProtocolBlock from 'Components/Surveys/ExaminationProtocol/ProtocolBlock/ProtocolBlock';
import ProtocolPlaceholderTitle
  from 'Components/Surveys/ExaminationProtocol/ProtocolPlaceholderTitle/ProtocolPlaceholderTitle';
import ProtocolSubtitleThree from 'Components/Surveys/ExaminationProtocol/ProtocolSubtitleThree/ProtocolSubtitleThree';
import ProtocolFormField from 'Components/Surveys/ExaminationProtocol/ProtocolFormField/ProtocolFormField';
import ProtocolRow from 'Components/Surveys/ExaminationProtocol/ProtocolRow/ProtocolRow';
import ProtocolResultTitle from 'Components/Surveys/ExaminationProtocol/ResultTitle/ResultTitle';
import ProtocolResultBlock from 'Components/Surveys/ExaminationProtocol/ProtocolResultBlock/ProtocolResultBlock';
import ProtocolResultWrapper from 'Components/Surveys/ExaminationProtocol/ProtocolResultWrapper/ProtocolResultWrapper';
import ProtocolBlockTitle from 'Components/Surveys/ExaminationProtocol/ProtocolBlockTitle/ProtocolBlockTitle';
import ProtocolDescriptionSubtitle
  from 'Components/Surveys/ExaminationProtocol/ProtocolResultTitle/ProtocolResultTitle';


const OnTheFarmPartThree = (props) => {

  const {
    register, errors, control, isConclusionDisabled, disabled, isLessonFinished
  } = props

  const { t } = useTranslation();

  return (
      <>
        <ProtocolBlock>
          <ProtocolPlaceholderTitle>{t('farm_game_part_3')}</ProtocolPlaceholderTitle>
          <ProtocolSubtitleThree>{t('agreement_noun_num')}</ProtocolSubtitleThree>

          <ProtocolRow>
            <ProtocolFormField
                type='text'
                label={t('one_white_chicken')}
                name='game_on_the_farm_part_three.one_white_chicken'
                register={register}
                errors={errors}
                disabled={disabled}
            />
          </ProtocolRow>
          <ProtocolRow>
            <ProtocolFormField
                type='text'
                label={t('three_red_haired_chicks')}
                name='game_on_the_farm_part_three.three_ginger_hens'
                register={register}
                errors={errors}
                disabled={disabled}
            />
          </ProtocolRow>
          <ProtocolRow>
            <ProtocolFormField
                type='text'
                label={t('chicken_with_five_spots')}
                name='game_on_the_farm_part_three.five_speckled_hens'
                register={register}
                errors={errors}
                disabled={disabled}
            />
          </ProtocolRow>
          {isLessonFinished && (
              <>
                <ProtocolResultTitle>{t('conclusion_options')}</ProtocolResultTitle>
                <ProtocolRow>
                  <ProtocolResultBlock>
                    <ProtocolResultWrapper>
                      <ProtocolFormField
                          type='radio'
                          label={t('the_child_mixes_paradigms_of_different_endings')}
                          name='game_on_the_farm_part_three.options_for_confinement'
                          control={control}
                          errors={errors}
                          disabled={isConclusionDisabled || disabled}
                      />
                    </ProtocolResultWrapper>
                    <ProtocolResultWrapper>
                      <ProtocolFormField
                          type='radio'
                          label={t('the_child_makes_mistakes_within_one_case')}
                          name='game_on_the_farm_part_three.options_for_confinement'
                          control={control}
                          errors={errors}
                          disabled={isConclusionDisabled || disabled}
                      />
                    </ProtocolResultWrapper>
                  </ProtocolResultBlock>
                </ProtocolRow>
              </>
          )}
          <ProtocolRow>
            <ProtocolFormField
                type='textarea'
                label={t('comment')}
                name='game_on_the_farm_part_three.expert_comment'
                placeholder={t('expert_comment')}
                register={register}
                disabled={disabled}
            />
          </ProtocolRow>
        </ProtocolBlock>
        {isLessonFinished && (
            <>
              <ProtocolBlock>
                <ProtocolBlockTitle>{t('psychological_base_of_speech_attention')}</ProtocolBlockTitle>
                <ProtocolResultTitle>{t('conclusion_options')}</ProtocolResultTitle>
                <ProtocolRow>
                  <ProtocolDescriptionSubtitle>{t('speech_attention')}</ProtocolDescriptionSubtitle>
                  <ProtocolResultBlock>
                    <ProtocolResultWrapper>
                      <ProtocolFormField
                          type='radio'
                          label={t('formed')}
                          name='game_on_the_farm_part_three.speech_comprehension'
                          control={control}
                          errors={errors}
                          disabled={isConclusionDisabled || disabled}
                      />
                    </ProtocolResultWrapper>
                    <ProtocolResultWrapper>
                      <ProtocolFormField
                          type='radio'
                          label={t('insufficiently_formed')}
                          name='game_on_the_farm_part_three.speech_comprehension'
                          control={control}
                          errors={errors}
                          disabled={isConclusionDisabled || disabled}
                      />
                    </ProtocolResultWrapper>
                    <ProtocolResultWrapper>
                      <ProtocolFormField
                          type='radio'
                          label={t('not_formed')}
                          name='game_on_the_farm_part_three.speech_comprehension'
                          control={control}
                          errors={errors}
                          disabled={isConclusionDisabled || disabled}
                      />
                    </ProtocolResultWrapper>
                  </ProtocolResultBlock>
                  <ProtocolDescriptionSubtitle>{t('distribution')}</ProtocolDescriptionSubtitle>
                  <ProtocolResultBlock>
                    <ProtocolResultWrapper>
                      <ProtocolFormField
                          type='checkbox'
                          label={t('difficulty_in_dividing_attention')}
                          name='game_on_the_farm_part_three.there_are_difficulties_in_distributing_attention'
                          control={control}
                          errors={errors}
                          disabled={isConclusionDisabled || disabled}
                      />
                    </ProtocolResultWrapper>
                  </ProtocolResultBlock>
                  <ProtocolDescriptionSubtitle>{t('concentration')}</ProtocolDescriptionSubtitle>
                  <ProtocolResultBlock>
                    <ProtocolResultWrapper>
                      <ProtocolFormField
                          type='radio'
                          label={t('low_concentration_and_instability_of_attention_in_general')}
                          name='game_on_the_farm_part_three.concentration'
                          control={control}
                          errors={errors}
                          disabled={isConclusionDisabled || disabled}
                      />
                    </ProtocolResultWrapper>
                    <ProtocolResultWrapper>
                      <ProtocolFormField
                          type='radio'
                          label={t('difficulty_concentrating_voluntary_attention')}
                          name='game_on_the_farm_part_three.concentration'
                          control={control}
                          errors={errors}
                          disabled={isConclusionDisabled || disabled}
                      />
                    </ProtocolResultWrapper>
                  </ProtocolResultBlock>
                  <ProtocolDescriptionSubtitle>{t('sustainability')}</ProtocolDescriptionSubtitle>
                  <ProtocolResultBlock>
                    <ProtocolResultWrapper>
                      <ProtocolFormField
                          type='radio'
                          label={t('attention_is_unstable_superficial_the_child_is_very_quickly_depleted')}
                          name='game_on_the_farm_part_three.sustainability'
                          control={control}
                          errors={errors}
                          disabled={isConclusionDisabled || disabled}
                      />
                    </ProtocolResultWrapper>
                    <ProtocolResultWrapper>
                      <ProtocolFormField
                          type='radio'
                          label={t('attention_is_not_stable_enough')}
                          name='game_on_the_farm_part_three.sustainability'
                          control={control}
                          errors={errors}
                          disabled={isConclusionDisabled || disabled}
                      />
                    </ProtocolResultWrapper>
                    <ProtocolResultWrapper>
                      <ProtocolFormField
                          type='radio'
                          label={t('steady_attention')}
                          name='game_on_the_farm_part_three.sustainability'
                          control={control}
                          errors={errors}
                          disabled={isConclusionDisabled || disabled}
                      />
                    </ProtocolResultWrapper>
                  </ProtocolResultBlock>
                  <ProtocolDescriptionSubtitle>{t('exhaustibility')}</ProtocolDescriptionSubtitle>
                  <ProtocolResultBlock>
                    <ProtocolResultWrapper>
                      <ProtocolFormField
                          type='checkbox'
                          label={t('the_attention_of_the_child_is_characterized_by_rapid_exhaustion')}
                          name='game_on_the_farm_part_three.child_s_attention_is_characterized_by_rapid_exhaustion'
                          control={control}
                          errors={errors}
                          disabled={isConclusionDisabled || disabled}
                      />
                    </ProtocolResultWrapper>
                  </ProtocolResultBlock>
                </ProtocolRow>
                <ProtocolRow>
                  <ProtocolFormField
                      type='text'
                      label={t('volume')}
                      name='game_on_the_farm_part_three.volume'
                      register={register}
                      errors={errors}
                      disabled={isConclusionDisabled || disabled}
                  />
                </ProtocolRow>
                <ProtocolRow>
                  <ProtocolFormField
                      type='text'
                      label={t('switchability')}
                      name='game_on_the_farm_part_three.switchability'
                      register={register}
                      errors={errors}
                      disabled={isConclusionDisabled || disabled}
                  />
                </ProtocolRow>
              </ProtocolBlock>
              <ProtocolBlock>
                <ProtocolBlockTitle>{t('psychological_base_of_speech_cognitive_activity_motivation_and_interest')}</ProtocolBlockTitle>
                <ProtocolRow>
                  <ProtocolFormField
                      type='text'
                      label={t('fatigue')}
                      name='game_on_the_farm_part_three.fatigue'
                      register={register}
                      errors={errors}
                      disabled={isConclusionDisabled || disabled}
                  />
                </ProtocolRow>
                <ProtocolRow>
                  <ProtocolFormField
                      type='text'
                      label={t('contact')}
                      name='game_on_the_farm_part_three.contact'
                      register={register}
                      errors={errors}
                      disabled={isConclusionDisabled || disabled}
                  />
                </ProtocolRow>
                <ProtocolRow>
                  <ProtocolFormField
                      type='text'
                      label={t('performance')}
                      name='game_on_the_farm_part_three.working_capacity'
                      register={register}
                      errors={errors}
                      disabled={isConclusionDisabled || disabled}
                  />
                </ProtocolRow>
                <ProtocolRow>
                  <ProtocolFormField
                      type='text'
                      label={t('motivation')}
                      name='game_on_the_farm_part_three.motivation'
                      register={register}
                      errors={errors}
                      disabled={isConclusionDisabled || disabled}
                  />
                </ProtocolRow>
                <ProtocolRow>
                  <ProtocolFormField
                      type='text'
                      label={t('interest')}
                      name='game_on_the_farm_part_three.interest'
                      register={register}
                      errors={errors}
                      disabled={isConclusionDisabled || disabled}
                  />
                </ProtocolRow>
                <ProtocolResultTitle>{t('conclusion_options')}</ProtocolResultTitle>
                <ProtocolRow>
                  <ProtocolResultWrapper>
                    <ProtocolFormField
                        type='radio'
                        label={t('extremely_low_cognitive_activity_and_motivation_for_subject_subject_game_activity')}
                        name='game_on_the_farm_part_three.options_for_confinement_psychological_basis'
                        control={control}
                        errors={errors}
                        disabled={isConclusionDisabled || disabled}
                    />
                  </ProtocolResultWrapper>
                  <ProtocolResultWrapper>
                    <ProtocolFormField
                        type='radio'
                        label={t('low_cognitive_activity_and_motivation_for_various_activities')}
                        name='game_on_the_farm_part_three.options_for_confinement_psychological_basis'
                        control={control}
                        errors={errors}
                        disabled={isConclusionDisabled || disabled}
                    />
                  </ProtocolResultWrapper>
                  <ProtocolResultWrapper>
                    <ProtocolFormField
                        type='radio'
                        label={t('there_is_some_lack_of_cognitive_activity_and_motivation_for_objective_activity')}
                        name='game_on_the_farm_part_three.options_for_confinement_psychological_basis'
                        control={control}
                        errors={errors}
                        disabled={isConclusionDisabled || disabled}
                    />
                  </ProtocolResultWrapper>
                  <ProtocolResultWrapper>
                    <ProtocolFormField
                        type='radio'
                        label={t('pronounced_cognitive_activity_and_motivation_for_subject_subject_game_activity')}
                        name='game_on_the_farm_part_three.options_for_confinement_psychological_basis'
                        control={control}
                        errors={errors}
                        disabled={isConclusionDisabled || disabled}
                    />
                  </ProtocolResultWrapper>
                </ProtocolRow>
              </ProtocolBlock>
            </>
        )}
        <ProtocolBlock>
          <ProtocolBlockTitle>{t('prosodic_side_of_speech')}</ProtocolBlockTitle>
          <ProtocolSubtitleThree>{t('components')}</ProtocolSubtitleThree>
          <ProtocolRow>
            <ProtocolDescriptionSubtitle>{t('voice')}</ProtocolDescriptionSubtitle>
            <ProtocolResultBlock>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('aphonia')}
                    name='game_on_the_farm_part_three.voice'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('dysphonia')}
                    name='game_on_the_farm_part_three.voice'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('normal')}
                    name='game_on_the_farm_part_three.voice'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
            </ProtocolResultBlock>
            <ProtocolResultBlock>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('hoarse')}
                    name='game_on_the_farm_part_three.voice_part_two'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('voiced')}
                    name='game_on_the_farm_part_three.voice_part_two'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
            </ProtocolResultBlock>
            <ProtocolResultBlock>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('loud')}
                    name='game_on_the_farm_part_three.voice_part_three'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('quiet')}
                    name='game_on_the_farm_part_three.voice_part_three'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
            </ProtocolResultBlock>
            <ProtocolResultBlock>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('squeaky')}
                    name='game_on_the_farm_part_three.voice_part_four'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('very_low')}
                    name='game_on_the_farm_part_three.voice_part_four'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
            </ProtocolResultBlock>
            <ProtocolResultBlock>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('unmodulated')}
                    name='game_on_the_farm_part_three.voice_part_five'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('weakly_modulated')}
                    name='game_on_the_farm_part_three.voice_part_five'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
            </ProtocolResultBlock>
            <ProtocolResultBlock>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='checkbox'
                    label={t('nasalized ')}
                    name='game_on_the_farm_part_three.nasalized_voice'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
            </ProtocolResultBlock>
            <ProtocolDescriptionSubtitle>{t('smoothness')}</ProtocolDescriptionSubtitle>
            <ProtocolResultBlock>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('speech_is_fluent')}
                    name='game_on_the_farm_part_three.smoothness'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('speech_is_not_fluent')}
                    name='game_on_the_farm_part_three.smoothness'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
            </ProtocolResultBlock>
            <ProtocolDescriptionSubtitle>{t('pace')}</ProtocolDescriptionSubtitle>
            <ProtocolResultBlock>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('normal')}
                    name='game_on_the_farm_part_three.pace'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('fast')}
                    name='game_on_the_farm_part_three.pace'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('slow')}
                    name='game_on_the_farm_part_three.pace'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('pathologically_accelerated')}
                    name='game_on_the_farm_part_three.pace'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('pathologically_slow')}
                    name='game_on_the_farm_part_three.pace'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
            </ProtocolResultBlock>
            <ProtocolDescriptionSubtitle>{t('speech')}</ProtocolDescriptionSubtitle>
            <ProtocolResultBlock>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('on_inspiration')}
                    name='game_on_the_farm_part_three.speech'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('on_exhalation')}
                    name='game_on_the_farm_part_three.speech'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('fades_towards_the_end_of_a_sentence')}
                    name='game_on_the_farm_part_three.speech'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
            </ProtocolResultBlock>
            <ProtocolDescriptionSubtitle>{t('breath')}</ProtocolDescriptionSubtitle>
            <ProtocolResultBlock>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('clavicular')}
                    name='game_on_the_farm_part_three.breath'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('breastfeeding')}
                    name='game_on_the_farm_part_three.breath'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('diaphragmatic')}
                    name='game_on_the_farm_part_three.breath'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('mixed')}
                    name='game_on_the_farm_part_three.breath'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
            </ProtocolResultBlock>
            <ProtocolResultBlock>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('expiration_is_shortened')}
                    name='game_on_the_farm_part_three.exhalation'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('exhale_smoothly')}
                    name='game_on_the_farm_part_three.exhalation'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
            </ProtocolResultBlock>
            <ProtocolResultBlock>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='checkbox'
                    label={t('difficult')}
                    name='game_on_the_farm_part_three.hindered'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='checkbox'
                    label={t('superficial')}
                    name='game_on_the_farm_part_three.superficial'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='checkbox'
                    label={t('non_rhythmic')}
                    name='game_on_the_farm_part_three.breathing_is_not_rhythmic'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='checkbox'
                    label={t('shallow_breath')}
                    name='game_on_the_farm_part_three.shallow_breath'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
              {errors.choices19 && <div className='form2__error'> {errors.choices19.message}</div>}
            </ProtocolResultBlock>
            <ProtocolDescriptionSubtitle>{t('rhythm')}</ProtocolDescriptionSubtitle>
            <ProtocolResultBlock>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('not_violated')}
                    name='game_on_the_farm_part_three.rhythm'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('disturbed_speech_is_stretched_chanted')}
                    name='game_on_the_farm_part_three.rhythm'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
            </ProtocolResultBlock>
            <ProtocolDescriptionSubtitle>{t('exhalation_force')}</ProtocolDescriptionSubtitle>
            <ProtocolResultBlock>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('weak')}
                    name='game_on_the_farm_part_three.expiratory_force'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('strong')}
                    name='game_on_the_farm_part_three.expiratory_force'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
            </ProtocolResultBlock>
            <ProtocolDescriptionSubtitle>{t('differentiation_of_inhalation_exhalation_and_the_ability_to_control_breathing')}</ProtocolDescriptionSubtitle>
            <ProtocolResultBlock>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('fine')}
                    name='game_on_the_farm_part_three.inspiratory_expiratory_differentiation'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
              <ProtocolResultWrapper>
                <ProtocolFormField
                    type='radio'
                    label={t('violated')}
                    name='game_on_the_farm_part_three.inspiratory_expiratory_differentiation'
                    control={control}
                    errors={errors}
                    disabled={disabled}
                />
              </ProtocolResultWrapper>
            </ProtocolResultBlock>
          </ProtocolRow>
          {isLessonFinished && (
              <>
                <ProtocolResultTitle>{t('conclusion_options')}</ProtocolResultTitle>
                <ProtocolRow>
                  <ProtocolResultBlock>
                    <ProtocolResultWrapper>
                      <ProtocolFormField
                          type='radio'
                          label={t('the_prosodic_organization_of_speech_is_characterized_by_inadequate_intonational_design of_the_utterance')}
                          name='game_on_the_farm_part_three.prosodic_side_of_speech'
                          control={control}
                          errors={errors}
                          disabled={disabled}
                      />
                    </ProtocolResultWrapper>
                    <ProtocolResultWrapper>
                      <ProtocolFormField
                          type='radio'
                          label={t('speech_intelligibility_is_somewhat_reduced_spee')}
                          name='game_on_the_farm_part_three.prosodic_side_of_speech'
                          control={control}
                          errors={errors}
                          disabled={disabled}
                      />
                    </ProtocolResultWrapper>
                    <ProtocolResultWrapper>
                      <ProtocolFormField
                          type='radio'
                          label={t('speech_is_intelligible_understandable_to_others')}
                          name='game_on_the_farm_part_three.prosodic_side_of_speech'
                          control={control}
                          errors={errors}
                          disabled={disabled}
                      />
                    </ProtocolResultWrapper>
                  </ProtocolResultBlock>
                  <ProtocolResultBlock>
                    <ProtocolResultWrapper>
                      <ProtocolFormField
                          type='radio'
                          label={t('speech_intonation_is_expressive')}
                          name='game_on_the_farm_part_three.speech_intonationally'
                          control={control}
                          errors={errors}
                          disabled={disabled}
                      />
                    </ProtocolResultWrapper>
                    <ProtocolResultWrapper>
                      <ProtocolFormField
                          type='radio'
                          label={t('speech_is_intonationally_inexpressive_weak_expressiveness_of_voice_modulationse')}
                          name='game_on_the_farm_part_three.speech_intonationally'
                          control={control}
                          errors={errors}
                          disabled={disabled}
                      />
                    </ProtocolResultWrapper>
                  </ProtocolResultBlock>
                </ProtocolRow>
                <ProtocolDescriptionSubtitle>{t('violation_of_the_tempo_rhythmic_organization_of_speech')}</ProtocolDescriptionSubtitle>
                <ProtocolResultBlock>
                  <ProtocolResultWrapper>
                    <ProtocolFormField
                        type='radio'
                        label={t('convulsions')}
                        name='game_on_the_farm_part_three.violation_of_tempo_rhythmic_organization_of_speech'
                        control={control}
                        errors={errors}
                        disabled={disabled}
                    />
                  </ProtocolResultWrapper>
                  <ProtocolResultWrapper>
                    <ProtocolFormField
                        type='radio'
                        label={t('hesitation')}
                        name='game_on_the_farm_part_three.violation_of_tempo_rhythmic_organization_of_speech'
                        control={control}
                        errors={errors}
                        disabled={disabled}
                    />
                  </ProtocolResultWrapper>
                </ProtocolResultBlock>
              </>
          )}
        </ProtocolBlock>
      </>
  );
};

export default OnTheFarmPartThree;
