export const GET_LESSON = 'GET_LESSON'
export const GET_LESSON_ERROR = 'GET_LESSON_ERROR'

export const CHANGE_ACTIVE_GAME = 'CHANGE_ACTIVE_GAME'

export const CHANGE_LESSON_STATUS = 'CHANGE_LESSON_STATUS'

export const DISCONNECT = 'DISCONNECT'

export const RESIZE_CHILD_WEBCAM = 'RESIZE_CHILD_WEBCAM'