const dummyData = {
  child_full_name: 'Test string',
  main_complaints_from_parents: 'Test string',
  for_what_purpose_did_you_turn_to_a_speech_therapist: 'Test string',

  sat_in: 'Test string',
  crawled_on_all_fours_into: 'Test string',
  went_to: 'Test string',
  learned_to_jump_on_two_legs_in: 'Test string',
  injury_infection_before_during_and_or_after_childbirth: 'Test string',

  babbling_in: 'Test string',
  first_words_in: 'Test string',
  first_short_phrases_in: 'Test string',
  speech_environment: 'Test string',
  neurological_status: 'Test string',
  vision: 'Test string',
  hearing: 'Test string',
  eating_behavior: 'Test string',
  present_and_past_diseases: 'Test string',
  drug_treatment: 'Test string',
  emotional_and_psychological_level: 'Test string',
  emotional_background_during_class: 'Test string',
  motivation_and_interest: 'Test string',
  mimic_manifestations: 'Test string',
  basic_emotions_that_it_exhibits: 'Test string',
  formation_of_ideas_about_world_around: 'Test string',
  in_a_time_space_situation: 'Test string',
  image_i: 'Test string',
  somatognosis: 'Test string',
  speech_comprehension_level: 'Test string',
  level_of_vocabulary_formation: 'Test string',
  active_semantic_component_active_vocabulary: 'Test string',
  systemic_vocabulary_organization: 'Test string',
  level_of_grammatical_competence_formation: 'Test string',
  inflectional_skills_and_abilities_part_one: 'Test string',
  inflectional_skills_and_abilities_part_two: 'Test string',
  level_of_formation_of_phonetic_phonological_competence: 'Test string',

  state_of_phonemic_perception: 'Test string',
  state_of_phonemic_hearing: 'Test string',
  formation_of_skills_of_sound_analysis_and_synthesis: 'Test string',

  phonological_sound_analysis_and_synthesis_skills: 'Test string',
  syllabic_structure_of_a_word: 'Test string',
  prosodic_side_of_speech: 'Test string',
  voice: 'Test string',
  smoothness: 'Test string',
  pace: 'Test string',
  speech_is_carried_out: 'Test string',
  breath: 'Test string',
  rhythm: 'Test string',
  understanding_the_text: 'Test string',
  text_production: 'Test string',
  reproduction_of_text: 'Test string',
  articulation_apparatus_structure: 'Test string',
  syntactic_skills_and_abilities: 'Test string',
  level_of_formation_of_phonemic_perception: 'Test string',
  state_of_phonemic_hearing_game_magic_exam: 'Test string',
  formation_of_the_skills_of_sound_analysis_and_synthesis: 'Test string',

  syllabic_structure_of_the_word: 'Test string',
  sound_articulating_side_of_speech: 'Test string',
  prosodic_side_of_speech_game_on_the_farm_part_three: 'Test string',
  smoothness_game_on_the_farm_part_three: 'Test string',
  pace_game_on_the_farm_part_three: 'Test string',
  speech_game_on_the_farm_part_three: 'Test string',
  breath_game_on_the_farm_part_three: 'Test string',
  rhythm_game_on_the_farm_part_three: 'Test string',
  understanding_the_text_game_how_the_mouse_could_not_sleep: 'Test string',

  text_production_game_how_the_mouse_could_not_sleep: 'Test string',
  reproduction_of_text_game_how_the_mouse_could_not_sleep: 'Test string',

  articulation_apparatus_structure_game_how_the_mouse_could: 'Test string',

  bilateral_motor_organization: 'Test string',
  simultaneous_visual_perception: 'Test string',
  attention: 'Test string',
  general_ideas_of_child_about_world_around_him: 'Test string',
  volume_vocabulary: 'Test string',
  system_organization_of_dictionary_associative_links: 'Test string',

  inflectional_skills_and_abilities: 'Test string',
  word_building_skills_and_abilities: 'Test string',
  syllabic_structure_of_word: 'Test string',
  prosodic_speech_design: 'Test string',
  motor_functions_of_articulatory_apparatus: 'Test string',
  oral_praxis: 'Test string',
  articulatory_praxis: 'Test string',
  speech_breathing_and_voice_production: 'Test string',
  exhalation_force: 'Test string',
  inspiratory_expiratory_differentiation: 'Test string',
  basic_motor_skills_and_state_of_coordinating_sphere: 'Test string',

  postural_control_of_calm_state: 'Test string',
  bilateral_motor_coordination: 'Test string',
  formation_of_motor_imitation: 'Test string',
  motor_functions_of_hands_and_fingers: 'Test string',
  verbal_memory: 'Test string',
  speech_attention: 'Test string',
  thinking_verbal_and_non_verbal_intelligence: 'Test string',
  features_of_early_speech_development: 'Test string',
  features_of_speech_environment_in_which_child: 'Test string',
  features_of_speech_behavior: 'Test string',
  neurological_status_and_condition: 'Test string',
  information_about_current_and_past_diseases: 'Test string',
  emotional_reaction: 'Test string',
  emotional_response_to_adult_emotion: 'Test string',
  in_case_of_failure_behaves: 'Test string',
  logopedic_conclusion: 'Test string',
  recommendation: 'Test string',
};

export default dummyData;
